### ISSUE TITLE
FAILED: render_utils_kernel.cuda.o

### ISSUE THREAD

**Issue by RedemptYourself** [hustvl/TiNeuVox#15]
D:/NERF/TiNeuVox-main/lib/cuda/render_utils_kernel.cu(368): error: calling a __host__ function("pow<double, float, (int)0> ") from a __global__ function("raw2alpha_cuda_kernel<double> ") is not allowed

D:/NERF/TiNeuVox-main/lib/cuda/render_utils_kernel.cu(368): error: identifier "pow<double, float, (int)0> " is undefined in device code

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\crt\math_functions.hpp(980): error: calling a __host__ function("pow<double, float, (int)0> ") from a __global__ function("raw2alpha_backward_cuda_
kernel<double> ") is not allowed

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\crt\math_functions.hpp(980): error: identifier "pow<double, float, (int)0> " is undefined in device code

4 errors detected in the compilation of "D:/NERF/TiNeuVox-main/lib/cuda/render_utils_kernel.cu".
render_utils_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\80920\.conda\envs\pymarl\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "C:\Users\80920\.conda\envs\pymarl\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 17, in <module>
    from lib import tineuvox, utils
  File "D:\NERF\TiNeuVox-main\lib\tineuvox.py", line 20, in <module>
    verbose=True)
  File "C:\Users\80920\.conda\envs\pymarl\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\80920\.conda\envs\pymarl\lib\site-packages\torch\utils\cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\80920\.conda\envs\pymarl\lib\site-packages\torch\utils\cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "C:\Users\80920\.conda\envs\pymarl\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'render_utils_cuda'

**Comment by XLionXL** [comment]
Voxurf?
